### ISSUE TITLE
Front-end for Task3

### ISSUE THREAD

**Issue by SAJ33L** [SAJ33L/BTW-Flask-Repo#19]
![Screenshot_20230428_090732_Chrome](https://user-images.githubusercontent.com/91918558/235051966-b8160ebf-bee4-46ca-b0d4-50097f0d6784.jpg)

**Comment by prashantjerk** [comment]
This is gonna be my first open source contribution. So, I want to go simple and try to learn how to all of these things. Therefore, I'll be sending a PR after the issue is resolved.

**Comment by prashantjerk** [comment]
I forked the repo, but I don't know how to get started. Am I supposed to start the live server `base.html` that is inside Task3/templates? If it is so, I tried doing it, but I only see `{% block content %} {% endblock %} ` this being displayed in the browser. So, what am I lacking, how can I display the thing that needs to be displayed.
here is the screenshot of the result: ![image](https://user-images.githubusercontent.com/108537435/235041857-edd61719-8e43-4dc1-afe8-e437fb56e9ac.png)

**Comment by prashantjerk** [comment]
Also, the thing is I've previously styled lots of html files, however I'm not used to with styling a HTML file and a python file at the same time. You guide me with how to start it, then I'll continue further.

**Comment by SAJ33L** [comment]
Basically, it's a flask application when you run a web app in flask, then these currly braces change into then content or data that comes from the server..
These are the kind of placeholders for the real data. So just let me know where you want further help. I will try to share a design with you to help you make one front-end.

**Comment by prashantjerk** [comment]
I just made a PR based on what I could see. If I were to see everything, I think I'd have made a good front-end with good animation. Since, I have never tried it, this is all I can do for now. However, if you can help me setup the system, and help me see things exactly the way it shows in your computer, let me know. I'd love to help you.

**Comment by SAJ33L** [comment]
Well I am also not a pro person but small contribution like this help alot to learn keep it up and surely you will able to do great.

**Comment by 0silverback0** [comment]
I would like to work on this task. Did you just need a simple frontend built with flask and templating the html with jinja? That is how I would design the front end of this flask app

**Comment by SAJ33L** [comment]
I would like to see your work if you can help me with it, and jinja seems to be great if you know how it works. there is a figma design I want the page to be like this

**Comment by 0silverback0** [comment]
@SAJ33L im starting work now doing some refactoring as well. Did you want the front end to look like the image at the top of the issue?

**Comment by SAJ33L** [comment]
@0silverback0 yes the plan is just to make the front-end more of simple and optimistic one.

**Comment by 0silverback0** [comment]
Hey I haven't heard from you how's everything going? Do you need any additional help?

**Comment by SAJ33L** [comment]
@0silverback0 not really I am good with the app thanks a lot for your concern, will reach out to you if I need some help. Best

**Comment by prashantjerk** [comment]
Hey there, I made the first PR to this issue of yours, and I wanted to look what your frontend looks like after that. Would you mind replying with the screenshot of the site you made?

**Comment by 0silverback0** [comment]
I didn't do anything to the front end but center the form in the middle of the page, everything else I did was just simple refactoring
